### ISSUE TITLE
Why "Run failed"?

### ISSUE THREAD

**Issue by Shunlexxi** [skills/.github#109]
### Discussed in https://github.com/orgs/skills/discussions/108

<div type='discussions-op-text'>

<sup>Originally posted by **Shunlexxi** November  7, 2022</sup>
On following some GitHub skill courses, I kept getting the above-mentioned error, please see attached for more info.

What does it mean and how do I fix it?

![Screenshot_20221107-225734](https://user-images.githubusercontent.com/51166816/200424881-5ad02a76-42f8-4c97-b7c1-1f9b9741cf35.png)
![Screenshot_20221107-225727](https://user-images.githubusercontent.com/51166816/200424907-44c2626a-bafb-43f9-9f96-6c900d5b7c31.png)
![Screenshot_20221107-225658](https://user-images.githubusercontent.com/51166816/200424912-f084b701-6361-4a75-a588-bd31139e6e00.png)
</div>

**Comment by Shunlexxi** [comment]
@heiskr @cheshire137 @koddsson @garnertb

**Comment by Sandeep-source** [comment]
@Shunlexxi 

Here what I got 

I you see failed workflow then you might find that it says that your branch is not up to date.
It also suggests to pull first then push these changes.

Here is what worked for me:
Simply create pull request from main to your new-branch and merge changes. Then rerun jobs [ workflows ].

**Comment by heiskr** [comment]
Thank you for opening an issue. It doesn't appear to contain information we can use to help diagnose the issue, but please let us know if the issue persists.
