### ISSUE TITLE
Question on how to start course for Module 2 / Github Learning Lab and migrating-your-repository

### ISSUE THREAD

**Issue by Learn5Git** [skills/.github#243]
### Discussed in https://github.com/orgs/skills/discussions/242

<div type='discussions-op-text'>

<sup>Originally posted by **Learn5Git** June  1, 2023</sup>
Hello, 

I am new to Github, and following the Microsoft Learn Github learning course plan, with multiple modules. I completed Module 1. In that module, there was a green button "Start Course" to click to start the course. 

I am now in the second Module "Migrating Your Repository". I see the readme file, and the goals of the course, but I don't see what to do, or how to start the course. There is no button to "Start Course" like there was for the first module. How are you supposed to proceed? 

If I click on the course name, it takes me to a 404 page: https://lab.github.com/githubtraining/migrating-your-repository-to-github

Could this be updated so people can complete this module?

Thank you.

06/01/2023</div>

**Comment by Learn5Git** [comment]
I need help in completting this Module (#2) in the Microsoft Learn course on learning GitHub. In this GitHub module, you are supposed to be directed to the Learning Lab, and proceed with the course for migrating your repository.

**Comment by hectorsector** [comment]
Thanks for the info, @Learn5Git! I've opened an issue with the team that looks after those modules at https://github.com/githubpartners/microsoft-learn/issues/71. I'm closing this one in favor of that.
