### ISSUE TITLE
Course feedback

### ISSUE THREAD

**Issue by TheDataAcademy** [skills/.github#393]
Started well but stuck on item 3 Add a code example, the worklflow is not working or flowing, it has been an interesting 2 days investigating and learning about how workflows are supposed to function but I am not wasting any more time, sorry GitHub A for effort, D for results.

**Comment by ICW3-ADMIN** [comment]
[skills](https://github.com/skills)

**Comment by hectorsector** [comment]
Thanks for taking the time write up some feedback, @TheDataAcademy. We use issues for bug tracking, but you can drop feedback in [Discussions](https://github.com/orgs/skills/discussions/359).
