### ISSUE TITLE
[Introduction to GitHub] Course feedback survey!

### ISSUE THREAD

**Issue by lucasoliveira002** [skills/.github#556]
1. I can't say exactly, but I think the part about editing a README file is interesting
2. I take a technical course in Systems Development and I'm in my 2nd year, I'm still a beginner, but I know the basics of commits, pull requests and merge
3. I had some difficulties creating a repository and editing the files contained therein, this course helped a lot with that part
4. Because I'm Brazilian, I think the language of the course was a bit of a hindrance, but nothing that would make it impossible for me to do it.
5. I would like to know more about shared projects
6. I intend to use github to post some activities that involve programming and develop some teamwork
7. I would highly recommend this course to any friend of mine who was just starting out.

**Comment by hectorsector** [comment]
Thanks for the feedback, @lucasoliveira002!
