### ISSUE TITLE
looking to auto assign these courses as soon as a new user is on-boarded

### ISSUE THREAD

**Issue by srkambham** [skills/.github#84]
### Discussed in https://github.com/orgs/skills/discussions/73

<div type='discussions-op-text'>

<sup>Originally posted by **srkambham** October 12, 2022</sup>
Hello All,

Looking to auto assign/trigger any of these courses while on-boarding a new user to the GitHub Enterprise cloud.
Please share your ideas/references/links or knowledge base to implement, thank you</div>

**Comment by heiskr** [comment]
Thank you for opening this issue. The Skills team currently does not support this capability, you will want to follow up with your account representative.
